"""initial migration

Revision ID: 31f036906507
Revises: 
Create Date: 2018-08-08 18:32:19.609549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f036906507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('is_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charts', 'is_show')
    # ### end Alembic commands ###
